import { daysFromToday, toDateInputValue } from "@/lib/date-utils";
import type { Goal, Habit, Project, Task } from "@/types/planning";

const now = () => new Date().toISOString();

export const mockProjects: Project[] = [
  {
    id: "project-life-os",
    name: "Life OS personal",
    description:
      "Construir un sistema semanal para tareas, habitos, objetivos y revision.",
    area: "Productividad",
    color: "bg-blue-500",
    taskIds: ["task-priorities", "task-week-plan", "task-review"],
  },
  {
    id: "project-health",
    name: "Energia y salud",
    description:
      "Mejorar energia diaria con entrenamiento, descanso y alimentacion.",
    area: "Salud",
    color: "bg-emerald-500",
    taskIds: ["task-workout", "task-meal-plan"],
  },
  {
    id: "project-learning",
    name: "Aprendizaje continuo",
    description: "Reservar bloques de estudio y consolidar notas utiles.",
    area: "Aprendizaje",
    color: "bg-violet-500",
    taskIds: ["task-study"],
  },
];

export const mockGoals: Goal[] = [
  {
    id: "goal-weekly-focus",
    title: "Completar 5 bloques de trabajo profundo",
    description: "Proteger sesiones sin interrupciones para avanzar lo clave.",
    area: "Productividad",
    current: 2,
    target: 5,
    unit: "bloques",
    dueDate: daysFromToday(5),
  },
  {
    id: "goal-health",
    title: "Entrenar 3 veces esta semana",
    description: "Mantener consistencia fisica sin sobrecargar la agenda.",
    area: "Salud",
    current: 1,
    target: 3,
    unit: "sesiones",
    dueDate: daysFromToday(6),
  },
  {
    id: "goal-review",
    title: "Cerrar la revision semanal",
    description: "Revisar pendientes, energia, aprendizajes y siguiente foco.",
    area: "Revision",
    current: 35,
    target: 100,
    unit: "%",
    dueDate: daysFromToday(7),
  },
];

export const mockHabits: Habit[] = [
  {
    id: "habit-water",
    name: "Agua y pausa activa",
    description: "Tomar agua y moverse al menos una vez por la manana.",
    category: "Salud",
    cadence: "daily",
    targetPerWeek: 7,
    completedDates: [daysFromToday(-1)],
  },
  {
    id: "habit-planning",
    name: "Plan de 10 minutos",
    description: "Definir top 3, calendario y primer siguiente paso.",
    category: "Productividad",
    cadence: "daily",
    targetPerWeek: 5,
    completedDates: [toDateInputValue(new Date())],
  },
  {
    id: "habit-reading",
    name: "Lectura enfocada",
    description: "Leer o estudiar sin multitarea durante 25 minutos.",
    category: "Aprendizaje",
    cadence: "weekly",
    targetPerWeek: 4,
    completedDates: [daysFromToday(-2), daysFromToday(-1)],
  },
];

export const mockTasks: Task[] = [
  {
    id: "task-priorities",
    title: "Definir prioridades del dia",
    description: "Elegir las 3 tareas que mas mueven la semana.",
    category: "Personal",
    priority: "high",
    status: "in_progress",
    dueDate: toDateInputValue(new Date()),
    plannedDate: toDateInputValue(new Date()),
    estimatedMinutes: 25,
    projectId: "project-life-os",
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "task-week-plan",
    title: "Bloquear plan semanal",
    description: "Asignar bloques de foco, salud y revision semanal.",
    category: "Trabajo",
    priority: "critical",
    status: "todo",
    dueDate: toDateInputValue(new Date()),
    plannedDate: toDateInputValue(new Date()),
    estimatedMinutes: 45,
    projectId: "project-life-os",
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "task-review",
    title: "Revisar lista de pendientes vencidos",
    description: "Reprogramar, eliminar o completar tareas atrasadas.",
    category: "Personal",
    priority: "high",
    status: "todo",
    dueDate: daysFromToday(-1),
    plannedDate: daysFromToday(-1),
    estimatedMinutes: 30,
    projectId: "project-life-os",
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "task-workout",
    title: "Entrenamiento de fuerza",
    description: "Sesion corta centrada en movilidad y fuerza base.",
    category: "Salud",
    priority: "medium",
    status: "todo",
    dueDate: daysFromToday(1),
    plannedDate: toDateInputValue(new Date()),
    estimatedMinutes: 50,
    projectId: "project-health",
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "task-meal-plan",
    title: "Preparar plan de comidas",
    description: "Planificar compras y comidas simples de la semana.",
    category: "Salud",
    priority: "medium",
    status: "done",
    dueDate: daysFromToday(2),
    plannedDate: daysFromToday(-1),
    estimatedMinutes: 40,
    projectId: "project-health",
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "task-study",
    title: "Estudiar sistema de productividad",
    description: "Sintetizar ideas para revision semanal y objetivos.",
    category: "Aprendizaje",
    priority: "low",
    status: "todo",
    dueDate: daysFromToday(4),
    plannedDate: daysFromToday(3),
    estimatedMinutes: 60,
    projectId: "project-learning",
    createdAt: now(),
    updatedAt: now(),
  },
];
